// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Payload struct {
	Number *string `json:"number"`
	Value  *int    `json:"value"`
}

type Word struct {
	Text string `json:"text"`
}
